### ISSUE TITLE
Entity not found when dimming ?

### ISSUE THREAD

**Issue by thundergreen** [Burningstone91/Hue_Dimmer_Deconz#13]
Hello First of all thanks for this awesome app. This reduces my automations a bit and it's just handy. Anyway.. when ich turn on / off light everything works fine but if I try to dim I get this error:

```2021-01-02 21:45:55 ERROR (MainThread) [homeassistant.components.deconz] Could not find the entity light.chill_out_corner```

very weird as on off works . Any idea here?

**Comment by Burningstone91** [comment]
Is `light.chill_out_corner` a deconz light? This app only works for deconz lights. 
Anyway, this app is soon going to be deprecated as I switched to using blueprints for this. I have it running already in my system and going to publish it once I tested it some more. I can share the code if you want.

**Comment by thundergreen** [comment]
Thanks for the info.i swapped to ZHa app works perfectly

**Comment by jokerigno** [comment]
what? I just installed it and now it becomes deprecated. :(

BWT I would love to test your code if you want. I have a HUE dimmer switch that would control a rgbw strip.

TY

**Comment by Burningstone91** [comment]
The introduction of blueprints made this basically obsolete. The only thing I haven't figured out yet is to control multiple lights, but I honestly don't see why this is needed, if I want to control multiple lights I just put them in a group and control the group instead. 

Please send me a PM in the HA forum, then I'll send you over the blueprint for testing. I'm using it for one week with 6 rwmotes and didn't have any issue so far..
