### ISSUE TITLE
Feature Request: Circle through a list of scene with a single click

### ISSUE THREAD

**Issue by schneekluth** [Burningstone91/Hue_Dimmer_Deconz#2]
I am currently migrating all my hue dimmers to deconz and really like your solution. There is just one thing I am missing: In the hue app you could distinct between 1 till 5 repeating clicks. I've used this to circle/rotate through a given list of scenes. Would it be possible to implement this feature in your appdaemon app?

![hue_dimmer](https://user-images.githubusercontent.com/5740913/72687480-75c26600-3afe-11ea-9af4-2e2e10ce7084.jpg)

**Comment by Burningstone91** [comment]
The problem is that deconz doesn't provide the events "double click", "triple click", etc.
I will see if I can work around this issue with some timestamp logic. I'll let you know

**Comment by Davst** [comment]
Upvote for this, would be great to have a configurable delay timer to watch for a button press for the same button. 

The other way for this would be to catch the 1001 press and on subsequent presses report this with a counter event or similar. 

this way you could make a listener that cycled scenes based on a number.. or... even better .. if it fetched the scenes from deconz available for that group and calculated that beforehand. (maybe not queriable from deconz though)

**Comment by schneekluth** [comment]
The more I think about this issue I'd like to see this function in hass core. There definetly are more types of devices that only support a single press like dash buttons or the upcoming IKEA shortcut button who could profit from this functionality. I'll open an official feature request for that in hass forum in prallel.

**Update**: https://community.home-assistant.io/t/functionality-to-cycle-through-a-given-list-of-scenes/174801

**Comment by X1pheR** [comment]
I'm also looking for this. It looks like this functionality is present in ControllerX: https://xaviml.github.io/controllerx/others/multiple-clicks
