### ISSUE TITLE
Dimming lights a bit up at the end

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [Burningstone91/Hue_Dimmer_Deconz#7]
When I use the default config and do down dimming it feels like the light is getting a little bit brighter, when stop the dimming.

Perhaps it is just in my case. But I ask other people in my house and they tell me the same.

**Comment by Burningstone91** [comment]
Could be possible, I don't know exactly how the deconz service works when it stops dimming, but I assume it reads the current brightness and then sets the light to this brightness, however as the dimming continues, it may be possible that the brightness decreased even more and therefore the brightness actually increases a bit when you stoo the dimming. This is just an assumption, anyway this is not a behaviour that I can change, this would need to be changed by the developers of deconz.
